/**
 * T-A: planner self-disclose integration
 *
 * Verifies the planner surface is aware of the new introspective acts:
 *   1. The system prompt names the new acts so the model can emit them.
 *   2. A phase whose allowedActs includes self_disclose surfaces them in the
 *      prompt's Allowed Acts list (no filtering drops them).
 */
import assert from 'node:assert/strict';
import test from 'node:test';
import { buildPlannerSystemPrompt } from '@/mastra/agents/planner';
import { createCharacterVersion, createPairState, createPhaseNode, createWorkingMemory } from '../persona-test-helpers';
import type { PlannerInput } from '@/mastra/agents/planner';

function buildPlannerInputWithSelfDiscloseAllowed(): PlannerInput {
  const characterVersion = createCharacterVersion();
  const phase = {
    ...createPhaseNode(),
    allowedActs: ['share_information', 'ask_question', 'self_disclose', 'show_vulnerability'] as any,
  };
  const pairState = createPairState({
    activeCharacterVersionId: characterVersion.id,
    activePhaseId: phase.id,
  });
  return {
    characterVersion,
    currentPhase: phase,
    pairState,
    emotion: pairState.emotion.combined,
    workingMemory: createWorkingMemory(),
    retrievedMemory: { events: [], facts: [], observations: [], threads: [] },
    userMessage: '最近どう？',
    recentDialogue: [],
    turnsSinceLastTransition: 1,
    daysSinceEntry: 1,
    turnsSinceLastEmotionUpdate: 1,
  } as unknown as PlannerInput;
}

test('planner system prompt names self_disclose and show_vulnerability as available acts', () => {
  const input = buildPlannerInputWithSelfDiscloseAllowed();
  const systemPrompt = buildPlannerSystemPrompt(input);

  assert.ok(
    systemPrompt.includes('self_disclose'),
    'system prompt must mention self_disclose somewhere'
  );
  assert.ok(
    systemPrompt.includes('show_vulnerability'),
    'system prompt must mention show_vulnerability somewhere'
  );
});

test('planner prompt Allowed Acts list includes self_disclose when the phase permits it', () => {
  const input = buildPlannerInputWithSelfDiscloseAllowed();
  const systemPrompt = buildPlannerSystemPrompt(input);

  // The allowed-acts block is generated by `currentPhase.allowedActs.map(...)`
  // — so adding an item to the phase config must flow into the prompt.
  assert.ok(
    /#### Allowed Acts[\s\S]*self_disclose/.test(systemPrompt),
    'Allowed Acts block must contain self_disclose'
  );
});
